### ISSUE TITLE
Plugin broken? (RH4-beta5)

### ISSUE THREAD

**Issue by hbickenbach** [RotorHazard/VRxC-ClearView2#1]
i used the VRX functions in RH3 successfull. In Rh4-beta5 they have moved to a plugin. I struggle using these plugin:

I downloaded the content of the vrx_cv2 folder into plugins. (tried main and v1.0.0-beta.)

The path .../src/server/plugins/vrx_cv2 conatins 3 files;
__init__.py
mqtt_topics.py
VRxCV1_emulator.py

I checked that the clearview library is installed. (I am using an venv for each Rotorhazard build, for easier switching of the versions. I took care of installing clearview to this venv like i did in RH3 before.)
After copying the plugin into the plugins folder Rotorhazard crashes on start

Exception ignored in: <function _removeHandlerRef at 0x7f4bbd38ac00>
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 855, in _removeHandlerRef
  File "/usr/lib/python3.11/logging/__init__.py", line 235, in _acquireLock
  File "/usr/lib/python3.11/threading.py", line 164, in acquire
  File "/home/linuxusername/RotorHazard-4.0.0-beta.5/.venv/lib/python3.11/site-packages/gevent/thread.py", line 74, in get_ident
TypeError: 'NoneType' object is not callable

after trying to start Rotorhazard there is an additional folder
__pycache__
in the plugin/vrx_cv2 folder

after removing the vrx_cv2 folder and all content in it RH4 beta5 starts again.

Can someone help me with this issue?

Thanks in advance
Heiko

**Comment by HazardCreative** [comment]
Thanks for the report. I don't believe this plugin has been updated for changes in the API made since RH4 beta 3. I'll take a look at it.

**Comment by HazardCreative** [comment]
Updated to latest API; functionality tested and confirmed.
