### ISSUE TITLE
backward compatibility: "Ready" message on VrxAll missing

### ISSUE THREAD

**Issue by hbickenbach** [RotorHazard/VRxC-ClearView2#3]
The old version of vrx implementation in rh 3.x.x send a message containing "Ready" to all, when a race is staged.

MQTT Message :
Topic: rx/cv1/cmd_esp_all
Payload: user_msg: "Ready"

i noticed that this message is not send anymore. An individual message containing "Pilotname Arm now" is send to each single seat.

I was using the "Ready" message to all as a trigger in one of my modifications.

Reimplementing this message is very easy, Ad the following line of code 
below line 151:     def onRaceStage(self, _args):

```
self.set_message_direct(VRxALL, self.racecontext.language.__("Ready"))
```

which will look like:

```
    def onRaceStage(self, _args):
        self.set_message_direct(VRxALL, self.racecontext.language.__("Ready"))
        seat_pilots = self.racecontext.race.node_pilots
        for seat in seat_pilots:
```

Maybe it is usefull to implement this in the plugin, maybe it helps someone else to reenable the message to be send to all

**Comment by HazardCreative** [comment]
"[name] arm now" is an improvement because it gives each user a chance to confirm their identity, and lets spectators know who they are viewing. This is the first message that is often seen because units are often kept off until needed.

It's best to use a more stable method for triggering other behaviors, such as a dedicated plugin with event handler.

**Comment by h-bickenbach** [comment]
Thank you for the explanation. I understand the new useful. behavior

I am already coding to use a plug in for the triggers.

**Comment by hbickenbach** [comment]
Thank you for the explanation. I understand the new useful. behavior

I am already coding to use a plug in for the triggers.
